apiVersion: v1
kind: Service
metadata:
  name: eshop-service
  namespace: default
spec:
  selector:
    app: eshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
