apiVersion: v1
kind: ConfigMap
metadata:
  name: eshop-config
  namespace: staging
data:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "eshop_staging"
  NODE_ENV: "staging"
