apiVersion: v1
kind: Secret
metadata:
  name: eshop-secret
  namespace: staging
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:REPLACE_WITH_STAGING_PASSWORD@postgres-service:5432/eshop_staging"
