apiVersion: v1
kind: ConfigMap
metadata:
  name: eshop-config
  namespace: production
data:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "eshop"
  NODE_ENV: "production"
