apiVersion: v1
kind: Secret
metadata:
  name: eshop-secret
  namespace: production
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:REPLACE_WITH_PROD_PASSWORD@postgres-service:5432/eshop"
